### ISSUE TITLE
Recover North Pole schematic

### ISSUE THREAD

**Issue by jflory7** [CrystalCraftMC/tasks#4]
I need to double-check my external hard drive at home for a backup of the North Pole schematic. If it exists, I need to add it to the server schematics so we can work with it on the development server.

**Comment by jflory7** [comment]
I checked for the North Pole schematic, but it's not on the disk. I found a few others and shared a screenshot in Slack.

**Comment by stevoism** [comment]
So here are the items that could be used for the north pole city revamp. I want to warn/advise that I do not know the build style, size or overall quality of these builds. The following items are taken out of my personal log while flipping through the schematic command. 

events_NorthPole2013_l134.schematic: SCHEMATIC
crystal.schematic: SCHEMATIC
santa_sleigh_forXMAS_16.schematic: SCHEMATIC
snowman_XMAS_16.schematic: SCHEMATIC
tree_XMAS_16.schematic: SCHEMATIC
xmas_dragon.schematic: SCHEMATIC
xmas_spawn_2016.schematic: SCHEMATIC

**Comment by jflory7** [comment]
> `events_NorthPole2013_l134.schematic: SCHEMATIC`
> `crystal.schematic: SCHEMATIC`
> `santa_sleigh_forXMAS_16.schematic: SCHEMATIC`
> `snowman_XMAS_16.schematic: SCHEMATIC`
> `tree_XMAS_16.schematic: SCHEMATIC`
> `xmas_dragon.schematic: SCHEMATIC`
> `xmas_spawn_2016.schematic: SCHEMATIC`
> `candycanes_XMAS_16`
> `daysleft_xmas_16`

These look like a good start for a fallback plan. Hopefully @dellman135 can work with some of these. ^^

**Comment by stevoism** [comment]
My concern with releasing a wild @dellman135 is that some may be to large. Only time will tell xD

**Comment by jflory7** [comment]
Since Dellman resigned, I don't think this is something we will be able to do this year. More info is explained in Slack.
